#!/usr/bin/env bash
#
#
# Initialises autocompletion for the Automation suite.

export BKT_CACHE_DIR="/tmp/bkt-${USER}"
export BKT_SCOPE="$$"
export BKT_TTL="1m"

completions=(branch create-pr)

for completion in ${completions[@]}; do
  if [ -f "./${completion}.completion" ]; then
    source "./${completion}.completion"
  fi
done

