#!/usr/bin/bash
#
#
# When executed using `source` (as done within the system-wide bashrc file),
# defines the `assert-success` function as follows:
#
# Asserts the given command runs successfully.
#
# Usage:
#   assert-success <prep-message> <command> <error-message> <exit-code> <success-message>
#
# Arguments:
#   <prep-message>      message to print before running command
#
#   <command>           command to run
#
#   <error-message>     error message to print on failure
#
#   <exit-code>         exit code to use on failure
#
#   <success-message>   success message to print on success

assert-success() {
    echo $1
    eval $2
    if [ $? -ne 0 ]; then
        echo "$3"
        echo -e "\nGoodbye..."
        exit $4
    fi
    echo -e $5
}
