#!/usr/bin/bash
#
#
# Determines the existence of files with the given file extension(s).
#
#
# Usage: find_by_extension <extension> [<extension> ...]
#
#
# Exit codes:
#   0 - if any files with the given extension(s) exist
#   1 - otherwise


to_ignore=("node_modules" "venv" "build" "dist" ".github" ".vscode")
# Add any directories that you want to ignore to the above array.
# The script will ignore all files in these directories.

max=${#to_ignore[@]}
index=1
prefix="-path '${to_ignore[0]}' -prune"

while [ ${index} -lt ${max} ]; do
    prefix="${prefix} -o -path '${to_ignore[${index}]}' -prune"
    index=$((index + 1))
done

max=$#
index=2
options="-name '$1'"
shift 1

while [ ${index} -le ${max} ]; do
    options="${options} -o -name '$1'"
    index=$((index + 1))
    shift 1
done

eval "find . \( ${prefix} \) -o \( ${options} \) | grep \"\""
