#!/usr/bin/bash
#
# Runs commands which initialise the local development environment after checking out a
# Git repository.
#
# These commands help to ensure that the local development environment is consistent
# across all developers working on all projects.



if [ ! -f "package.json" ]; then
    echo "Initializing npm project..."
    npm init -y > /dev/null
fi

echo "Installing dependencies..."
npm install > /dev/null

echo "Installing latest version of Prettier..."
npm install prettier --save-dev > /dev/null

if [ ! -f ".prettierrc.json" || ! -f ".prettierignore" ]; then
    echo "Ensuring Prettier configuration files are present..."
    if [ ! -f ".prettierrc.json" ]; then
        cp /usr/local/share/style/prettierrc.json .prettierrc.json > /dev/null
    fi
    if [ ! -f ".prettierignore" ]; then
        cp /usr/local/share/style/prettierignore .prettierignore > /dev/null
    fi
fi


find-by-extension ".py" > /dev/null
if [ $? -eq 0 ]; then
    echo "Found Python!"

    if [ ! -d "venv" ]; then
        echo "Creating virtual environment..."
        python3 -m venv venv > /dev/null
    fi

    source venv/bin/activate > /dev/null

    echo "Ensuring updated depencencies (including Black) are installed..."
    pip install --upgrade pip > /dev/null
    pip install black isort > /dev/null

    if [ -f "requirements.txt" ]; then
        pip install --requirement requirements.txt > /dev/null
    fi

    pip freeze > requirements.txt
fi
