#!/usr/bin/bash
#
# Runs commands which ensure the required formatters are installed and that the
# required files are formatted before committing.
#
# These commands help to ensure that the codebase is formatted consistently across
# projects, regarless of the developer or their development environment.


if [ -d "venv" ]; then
    source venv/bin/activate > /dev/null
    pip freeze > requirements.txt
    git add requirements.txt
fi

if [ -f "package.json" ]; then
    git add package.json package-lock.json
fi

git diff --staged --name-only \
    | xargs -I % echo "[ -f % ] && [[ % =~ .py ]] && black % && isort --profile black % || exit 0" \
    | sh

git diff --staged --name-only \
    | xargs -I % echo "[ -f % ] && [[ % =~ .html|.html.jinja|.css|.json|.js|.ts|.jsx|.tsx|.cjs ]] && npx prettier --write % || exit 0" \
    | sh

git diff --staged --name-only \
    | xargs -I % echo "[ -f % ] && git add % || exit 0" \
    | sh
