#!/usr/bin/bash
#
#
# Pushes the contents of the test branch to the production branch of the
# repository cloned into the current working directory, pulls the changes to the
# local working copy and restarts the production service.
#
# Usage:
#   prod [-t <test-branch>] [-p <prod-branch>] [-s <service-name>]
#        [-n <request-name> [-d <description>] [-f <directory>] [-r]
#   prod -h
#
# Options:
#   -t <test-branch>      Name of the branch from which to pull changes.
#                         Defaults to "test".
#
#   -p <prod-branch>      Name of the branch into which to push changes.
#                         Defaults to "prod".
#
#   -s <service-name>     Name of the production service to restart.
#                         Defaults to the name of the current working directory.
#
#   -n <request-name>     Title for the pull request.
#                         Defaults to "Pushed to production".
#
#   -d <description>      Description for the pull request.
#                         Defaults to the empty string.
#
#   -f <directory>        Directory into which to pull the updated production branch.
#                         Defaults to "/var/www/prod/<service-name>".
#
#   -r                    Do not restart the production service.
#
#   -h                    Display help and exit.
#
#
# Exit codes:
#   0 - success
#   1 - incorrect usage
#   2 - GitHub error
#   3 - directory error
#   4 - Python error
#   5 - NPM error
#   6 - service error


# exit codes
SUCCESS=0
INCORRECT_USAGE=1
GITHUB_ERROR=2
DIRECTORY_ERROR=3
PYTHON_ERROR=4
NPM_ERROR=5
SERVICE_ERROR=6


#######################################
# Display help message.
# Arguments:
#   None
# Outputs:
#   Writes help message to stdout
#######################################
showhelp() {
cat << EOF
Usage:
  prod [-t <test-branch>] [-p <prod-branch>] [-s <service-name>]
       [-n <request-name>] [-d <description>] [-f <directory>]
  prod -h

Pushes the contents of the test branch to the production branch of the
repository cloned into the current working directory, pulls the changes to the
local working copy of the production branch and restarts the production service.

Options:
    -t <test-branch>    Name of the branch from which to pull changes.
                        Defaults to "test".

    -p <prod-branch>    Name of the branch into which to push changes.
                        Defaults to "prod".

    -s <service-name>   Name of the production service to restart.
                        Defaults to the name of the current working directory.

    -n <request-name>   Title for the pull request.
                        Defaults to "Pushed to production".

    -d <description>    Description for the pull request.
                        Defaults to the empty string.

    -f <directory>      Directory into which to pull the updated production branch.
                        Defaults to "/var/www/prod/<service-name>".

    -r                  Do not restart the production service.

    -h                  Display help and exit.
EOF
}


# assign branch and service variables according to given arguments
while getopts ":t:p:s:n:d:f:rh" flag; do
    case "${flag}" in
        t) testb="${OPTARG}" ;;
        p) prod="${OPTARG}" ;;
        s) serv="${OPTARG}" ;;
        n) name="${OPTARG}" ;;
        d) desc="${OPTARG}" ;;
        f) prodp="${OPTARG}" ;;
        r) restart=0 ;;
        h) showhelp; exit ${SUCCESS} ;;
        ?) showhelp; exit ${INCORRECT_USAGE} ;;
    esac
done

# set default values for unset variables
## GitHub variables
testb=${testb:="test"}
prod=${prod:="prod"}
name=${name:="Pushed to production"}
desc=${desc:=""}
## service variables
serv=${serv:="$(basename ${PWD})"}
restart=${restart:=1}
prodp=${prodp:="/var/www/prod/${serv}"}


assert-success "Creating pull request..." \
               "gh pr create --base '${prod}' --head '${testb}' --title '${name}' --body '${desc}'" \
               "Error creating pull request" \
               ${GITHUB_ERROR} \
               "Pull request created\n"


assert-success "Merging pull request..." \
               "gh pr merge ${testb} --merge" \
               "Error merging pull request" \
               ${GITHUB_ERROR} \
               "Pull request merged\n"


assert-success "Entering production working directory..." \
               "cd ${prodp}" \
               "Error entering production working directory" \
               ${DIRECTORY_ERROR} \
               "Entered production working directory\n"


assert-success "Pulling production branch to working copy..." \
               "git pull" \
               "Error pulling production branch to working copy" \
               ${GITHUB_ERROR} \
               "Production branch pulled\n"


if [ -f "venv" -a -f "requirements.txt" ]; then
    assert-success "Activating virtual environment..." \
                   "source ${prodp}/venv/bin/activate" \
                   "Error activating virtual environment" \
                   ${PYTHON_ERROR} \
                   "Virtual environment activated\n"

    assert-success "Installing requirements..." \
                   "pip install -r requirements.txt" \
                   "Error installing requirements" \
                   ${PYTHON_ERROR} \
                   "Requirements installed\n"

    assert-success "Deactivating virtual environment..." \
                   "deactivate" \
                   "Error deactivating virtual environment" \
                   ${PYTHON_ERROR} \
                   "Virtual environment deactivated\n"
fi


if [ -f "package.json" -a -f "package-lock.json" ]; then
    assert-success "Installing NPM dependencies..." \
                   "npm install" \
                   "Error installing dependencies" \
                   ${NPM_ERROR} \
                   "Dependencies installed\n"
fi


if [ ${restart} ]; then
    assert-success "Restarting ${serv}.service..." \
                   "sudo service ${serv} restart" \
                   "Error restarting ${serv}.service" \
                   ${SERVICE_ERROR} \
                   "${serv}.service restarted\n"
fi


echo "Goodbye..."
exit ${SUCCESS}

